# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e51e2f0f1881ba6538588203e107f3239c82938fa2de457b0bda7684c581a5850505d8f91a3b2859c87bdd0e5c5cff1bd4e234e28349c930cabdc947520904

test:
  secret_key_base: 2d7c41842becbe46a0b6bce65d5f1705d1b1d2457091d86ff5b62d639cd7f486d78861f7d4bcc773d8a2ec94eecd3392856f1c9741ce74a05faf2d19f98ba6f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
